spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/spring
    username: admin
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update